config/routes.rb
Rails.application.routes.draw do

  resources :usuarios
  
  root             'home#index'
  get 'ajuda'   => 'estaticas#ajuda'
  get 'sobre'   => 'estaticas#sobre'
  get 'contato' => 'estaticas#contato'
  get 'signup'  => 'users#new'

  get 'login'   => 'sessao#new'
  post 'login'   => 'sessao#create'
  delete 'logout'   => 'sessao#destroy'

end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
	attr_accessor :remember_token
	
	def self.search(query)
		query = "%#{query}%"
  		nomeCompleto_match = arel_table[:nomeCompleto].matches(query)
  		where(nomeCompleto_match)
	end
  
  def remember
    self.remember_token = Usuario.new_token
    update_attribute(:remember_digest, Usuario.digest(remember_token))
  end

	mount_uploader :foto, PictureUploader
	validates :login, uniqueness: { case_sensitive: false, :message => "ja existe!"}	
	validates_presence_of :login, :message => "não pode ser vazio!"
	validates_presence_of :senha, :message => "não pode ser vazio!"
	validates :senha, length: { minimum: 6, :message => "muito curta (minimo 6 caracteres)"}
	validates_presence_of :nomeCompleto, :message => "não pode ser vazio!"
	validates_presence_of :foto, :message => "não pode ser vazio!"
	validates_presence_of :cidade, :message => "não pode ser vazio!"
	validates_presence_of :estado, :message => "não pode ser vazio!"
	validates_presence_of :email, :message => "não pode ser vazio!"
	validates :email, uniqueness: { case_sensitive: false, :message => "ja existe!" }
	validates_format_of :email, :with => /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/, :message => "inválido!"
	validates_presence_of :descricaoPessoal, :message => "não pode ser vazio!"
	validates :descricaoPessoal, length: {maximum: 255,  :message => "muito longa! Maximo de 255 caracteres"}
	validate :foto_size

	def Usuario.new_token
    SecureRandom.urlsafe_base64
  end

	def foto_size
      if foto.size > 5.megabytes
        errors.add(:foto, "deve ser menor que 5MB")
      end
    end

	def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

	def forget
    update_attribute(:remember_digest, nil)
  end

	def Usuario.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessaoHelper
	helper_method :random

	def random
	@registros = Usuario.count('nomeCompleto', :distinct => true)
	if (@registros < 5)
    	@random_no = @registros
    	@random ||= Usuario.order('RANDOM()').limit(@random_no)
		@random.map do |usuario|
   		usuario
  		end
	 else
		@random ||= Usuario.order('RANDOM()').limit(5)
	 end
	end
end

app/controllers/estaticas_controller.rb
class EstaticasController < ApplicationController
  def login
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/sessao_controller.rb
class SessaoController < ApplicationController
  def new
  end

  def create
	 usuario = Usuario.where(:login => params[:sessao][:login].downcase).first
    if usuario && usuario.senha.to_s == (params[:sessao][:senha]).to_s
		log_in usuario
		params[:sessao][:remember_me] == '1' ? remember(usuario) : forget(usuario)
		remember usuario
		redirect_back_or usuario
	 else 
	 	flash[:danger] = 'Combinacao login/senha inválida!' # Not quite right!
	 	render 'new'
	 end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :destroy, :show]
  before_action :correct_user,   only: [:edit, :update, :destroy]
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

	def logged_in_user
		unless logged_in?
			store_location
			flash[:danger] = "Por favor! Logue para obter acesso a pagina!."
			redirect_to login_url
		end
	end

	def correct_user
      @user = Usuario.find(params[:id])
      redirect_to(root_url) unless @user == current_user
    end

  # GET /usuarios
  # GET /usuarios.json
  def index
    if params[:search]
      @usuarios = Usuario.search(params[:search]).order("created_at DESC")
    else
      @usuarios = Usuario.order("created_at DESC")
    end
  end

	# GET /usuarios/random
	

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
		  flash[:success] = "Cadastro realizado com sucesso! Bem-vindo ao site!"
		  log_in @usuario
        format.html { redirect_to @usuario}
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

	def usuario_params
      params.require(:usuario).permit(:login, :senha, :nomeCompleto, :foto, :cidade, :estado, :email, :descricaoPessoal)
    end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    @usuario = Usuario.find(params[:id])
    if @usuario.update_attributes(usuario_params)
		flash[:success] = "Dados alterados com sucesso!"
      redirect_to @usuario
    else
      render 'edit'
    end
      
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    Usuario.find(params[:id]).destroy
    flash[:success] = "Usuario excluido!"
    redirect_to root_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:login, :senha, :foto, :nomeCompleto, :cidade, :estado, :email, :descricaoPessoal)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/estaticas_helper.rb
module EstaticasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/principais_helper.rb
module PrincipaisHelper
end

app/helpers/sessao_helper.rb
module SessaoHelper

# Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.url if request.get?
  end

def log_in(usuario)
    session[:usuario_id] = usuario.id
  end

def remember(usuario)
    usuario.remember
    cookies.permanent.signed[:usuario_id] = usuario.id
    cookies.permanent[:remember_token] = usuario.remember_token
  end

def current_user
	 if (usuario_id = session[:usuario_id])
      @current_user ||= Usuario.find_by(id: usuario_id)
    elsif (usuario_id = cookies.signed[:usuario_id])
      usuario = Usuario.find_by(id: usuario_id)
      if usuario && usuario.authenticated?(cookies[:remember_token])
        log_in usuario
        @current_user = usuario
      end
    end
  end

def current_user?(usuario)
    usuario == current_user
  end

def logged_in?
    !current_user.nil?
  end

def log_out
	 forget(current_user)
    session.delete(:usuario_id)
    @current_user = nil
  end

def forget(usuario)
    usuario.forget
    cookies.delete(:usuario_id)
    cookies.delete(:remember_token)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/compartilhado/_error_messages.html.erb
<% if @usuario.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      O formulário contem <%= pluralize(@usuario.errors.count, "erros") %>.
    </div>
    <ul>
    <% @usuario.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/estaticas/ajuda.html.erb
<% provide(:title, "Ajuda") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Projeto Final de Topicos</title>
  </head>
  <body>
    <p id="notice"><%= notice %></p>
		<div class="center jumbotron">
			<h1>Referencias</h1>
	<br/>
		  <h3>
		    <a href="http://hashrocket.com/blog/posts/rails-quick-tips-random-records">Obtendo usuários randomicamente para o carousel</a>
		  </h3>
		  <h3>
		    <a href="http://stackoverflow.com/questions/10714119/ruby-on-rails-call-controller-method-from-a-view">Usuarios random na index</a>
		  </h3>
		  <h3>
		    <a href="http://www.uberobert.com/rails_cloudinary_carrierwave/">Cloudinary e Carrierwave (manipulação de imagens)</a>
		  </h3>
		  <h3>
		    <a href="http://guides.railsgirls.com/heroku/">Guia para deploys e submits em Heroku</a>
		  </h3>
		  <h3>
		    <a href="http://stackoverflow.com/questions/4770133/rails-regex-for-email-validation">Regex para validação de emails</a>
		  </h3>
</div>
  </body>
</html>

app/views/estaticas/contato.html.erb
<% provide(:title, "Contato") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Projeto Final de Topicos</title>
  </head>
  <body>
    <p id="notice"><%= notice %></p>
		<div class="center jumbotron">
			<h1>Contato</h1>
	<br/>
		  <h3>
		    Adriano Cesar Bocoli - a11002@bcc.unifal-mg.edu.br
		  </h3>
		  <h3>
		    Anderson Luis dos Santos Selenguini - a11035@bcc.unifal-mg.edu.br
		  </h3>
</div>
  </body>
</html>

app/views/estaticas/login.html.erb
	<div class="wrapper">
		<h1>Login</h1>
		<div class="content">
			<div id="form_wrapper" class="form_wrapper">
				<form class="register">
					<h3>Register</h3>
					<div class="column">
						<div>
							<label>First Name:</label>
							<input type="text" />
							<span class="error">This is an error</span>
						</div>
						<div>
							<label>Last Name:</label>
							<input type="text" />
							<span class="error">This is an error</span>
						</div>
						<div>
							<label>Website:</label>
							<input type="text" value="http://"/>
							<span class="error">This is an error</span>
						</div>
					</div>
					<div class="column">
						<div>
							<label>Username:</label>
							<input type="text"/>
							<span class="error">This is an error</span>
						</div>
						<div>
							<label>Email:</label>
							<input type="text" />
							<span class="error">This is an error</span>
						</div>
						<div>
							<label>Password:</label>
							<input type="password" />
							<span class="error">This is an error</span>
						</div>
					</div>
					<div class="bottom">
						<div class="remember">
							<input type="checkbox" />
							<span>Send me updates</span>
						</div>
						<input type="submit" value="Register" />
						<a href="index.html" rel="login" class="linkform">You have an account already? Log in here</a>
						<div class="clear"></div>
					</div>
				</form>
				<form class="login active">
					<h3>Login</h3>
					<div>
						<label>Usuário:</label>
						<input type="text" />
						<span class="error">Erro!</span>
					</div>
					<div>
						<label>Senha:</label>
						<input type="password" />
						<span class="error">Erro!</span>
					</div>
					<div class="bottom">
						<input type="submit" value="Login" class="btn btn-lg btn-primary"></input>
						<%= link_to "Não possui uma conta? Registre-se aqui!", 'usuarios/new', class: "linkform" %>
						<div class="clear"></div>
					</div>
				</form>
			</div>
			<div class="clear"></div>
		</div>
		<a class="back" href="http://tympanus.net/codrops/2011/01/06/animated-form-switching/">back to the Codrops tutorial</a>
	</div>

app/views/estaticas/sobre.html.erb
<% provide(:title, "Sobre") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Projeto Final de Topicos</title>
  </head>
  <body>
    <p id="notice"><%= notice %></p>
		<div class="center jumbotron">
			<h1>Sobre</h1>
	<br/>
		  <h3>
		  		Projeto desenvolvido com o intuito de obter nota parcial na disciplina de Tópicos Especiais em Computação.
				Todas as referencias utilizadas estão descritas na página Ajuda e Referencias.
				
				Alfenas, Minas Gerais. 
		  </h3>

</div>
  </body>
</html>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Projeto criado usando o <a href="http://www.railstutorial.org/">Tutorial de Ruby on Rails</a>
    de <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Sobre",   'sobre' %></li>
      <li><%= link_to "Contato", 'contato' %></li>
      <li><a href="http://www.unifal-mg.edu.br">Unifal-MG</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container">
    <%= link_to "Pro.Fi.T.E.C.", '/', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to "Home",   '/' %></li>
        <li><%= link_to "Referencias",   ajuda_path %></li>
        <% if logged_in? %>
           <li><%= link_to "Usuários", usuarios_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Minha Conta <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Meus dados", current_user %></li>
              <li><%= link_to "Atualizar cadastro", edit_usuario_path(current_user) %></li>
     			  <li><%= link_to "Excluir conta!", current_user, method: :delete,
                                  data: { confirm: "Voce tem certeza?" } %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
			<%= form_tag(usuarios_path, :method => "get", class:"navbar-form navbar-left", id: "search-form", role:"search") do %>
    	  		<div class="input-group">
      			<%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Buscar usuarios" %>
					<span class="input-group-btn">
        				<button class="btn btn-default" type="submit" style="height:30px;">Pesquisar!</button>
      			</span>
				</div>
 		  <% end %>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
			 <li><%= link_to "Cadastre-se!", 'usuarios/new' %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
     <title><%= yield(:title) %> | Projeto Final de Topicos</title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>
  </head>
  <body>
	<%= render 'layouts/header' %>
    <div class="container">
		<% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
		 <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/sessao/new.html.erb
	<div class="wrapper">
		<div class="content">
			<div id="form_wrapper" class="form_wrapper">	
				<h3>Login</h3>			
				<%= form_for(:sessao, url: login_path, :html => {:class => "login active"}) do |f| %>
				<div>
      			<%= f.label :login%>
      			<%= f.text_field :login, class: 'form-control' %>
				</div>
				<div>
      			<%= f.label :senha %>
      			<%= f.password_field :senha, class: 'form-control' %>
				</div>
				<div class="bottom">
					<div class="clear"></div>
				<div class="checkbox inline">
					<%= f.label :remember_me do %>
        			<%= f.check_box :remember_me %><span>Lembrar-me!</span>
					<% end %>
					
					</div>
      			<%= f.submit "Log in", class: "btn btn-primary" %>
    				<% end %>
					<p><%= link_to "Novo usuário? Cadastre-se!", 'usuarios/new', class: "linkform" %></p>
				</div>
			</div>
			<div class="clear"></div>
		</div>
	</div>

app/views/users/new.html.erb
<h1>Sign up</h1>
<p>This will be a signup page for new users.</p>

app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :login %><br>
    <%= f.text_field :login %>
  </div>
  <div class="field">
    <%= f.label :senha %><br>
    <%= f.text_field :senha %>
  </div>
  <div class="field">
    <%= f.label :foto %><br>
    <%= f.text_field :foto %>
  </div>
  <div class="field">
    <%= f.label :nomeCompleto %><br>
    <%= f.text_field :nomeCompleto %>
  </div>
  <div class="field">
    <%= f.label :cidade %><br>
    <%= f.text_field :cidade %>
  </div>
  <div class="field">
    <%= f.label :estado %><br>
    <%= f.text_field :estado %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :descricaoPessoal %><br>
    <%= f.text_field :descricaoPessoal %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Atualize seu Cadastro</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

	 <%= form_for(@usuario) do |f| %>
		<%= render 'compartilhado/error_messages' %>

      <%= f.label :login, "Usuario" %>
      <%= f.text_field :login, class: 'form-control' %>

      <%= f.label :senha, "Senha"%>
      <%= f.password_field :senha, class: 'form-control'  %>

      <%= f.label :nomeCompleto, "Nome Completo" %>
      <%= f.text_field :nomeCompleto, class: 'form-control'  %>

      <%= f.label :foto, "Foto" %>
      <%= f.file_field :foto, accept: 'image/jpeg,image/gif,image/png', class: 'form-control'  %>
	
		<%= f.label :cidade, "Cidade" %>
      <%= f.text_field :cidade, class: 'form-control'  %>

		<%= f.label :estado, "Estado" %>
      <%= f.text_field :estado, class: 'form-control'  %>
		
		<%= f.label :email, "Email" %>
      <%= f.text_field :email, class: 'form-control'  %>

		<%= f.label :descricaoPessoal, "Descrição Pessoal" %>
      <%= f.text_field :descricaoPessoal, class: 'form-control'  %>

      <%= f.submit "Salvar alterações!", class: "btn btn-primary" %>
    <% end %>

	<script type="text/javascript">
  $('#usuario_foto').bind('change', function() {
    size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Tamanho maximo de arquivo 5MB. Escolha um arquivo menor.');
    }
  });
</script>
  </div>
</div>

app/views/usuarios/index.html.erb
<h1>Usuários </h1>

<ul class="users">
  <% if @usuarios.empty? %>
  	<script language="JavaScript">
   	alert("<%= @popup_message %> Nenhum usuário encontrado!!");
  	</script>
	<% end %>

  <% @usuarios.each do |usuario| %>
    <li>
		<% unless usuario.foto_url.nil? %><%= link_to (cl_image_tag usuario.foto_url(:small_avatar)), usuario %><% end %>
      <%= link_to usuario.nomeCompleto, usuario %>
    </li>
  <% end %>
</ul>

app/views/usuarios/new.html.erb
<h1>Cadastre-se</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@usuario, html: { multipart: true }) do |f| %>
		<%= render 'compartilhado/error_messages' %>

      <%= f.label :login, "Usuario" %>
      <%= f.text_field :login, class: 'form-control' %>

      <%= f.label :senha, "Senha"%>
      <%= f.password_field :senha, class: 'form-control'  %>

      <%= f.label :nomeCompleto, "Nome Completo" %>
      <%= f.text_field :nomeCompleto, class: 'form-control'  %>

      <%= f.label :foto, "Foto" %>
      <%= f.file_field :foto, accept: 'image/jpeg,image/gif,image/png', class: 'form-control'  %>
	
		<%= f.label :cidade, "Cidade" %>
      <%= f.text_field :cidade, class: 'form-control'  %>

		<%= f.label :estado, "Estado" %>
      <%= f.text_field :estado, class: 'form-control'  %>
		
		<%= f.label :email, "Email" %>
      <%= f.text_field :email, class: 'form-control'  %>

		<%= f.label :descricaoPessoal, "Descrição Pessoal" %>
      <%= f.text_field :descricaoPessoal, class: 'form-control'  %>

      <%= f.submit "Criar minha conta!", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $('#usuario_foto').bind('change', function() {
    size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Tamanho maximo de arquivo 5MB. Escolha um arquivo menor.');
    }
  });
</script>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Informações do usuário <%= @usuario.nomeCompleto %></h1>
<head>
	<link media="all" rel="stylesheet" type="text/css" href="app/assets/stylesheets/all.css" />
	<script type="text/javascript" src="js/jquery-1.7.1.min.js"></script>
	<script type="text/javascript" src="js/jquery.main.js"></script>
</head>
	<!--page-->
		<!--wrapper-->
		<div id="wrapper">
			<!--main-->
			<div id="main">
				<div class="main-holder">
					<div class="main-frame">
						<div class="main-content">
							<!--container-->
							<div class="container">
								<!--sidebar-->
								<div id="sidebar">
								<!--photo-->
								<div class="photo"><% unless @usuario.foto_url.nil? %><%= cl_image_tag @usuario.foto_url(:large_avatar) %><br /><% end %>
								</div>
								</div>
								<!--content-->
								<div id="content">
									<!--text-->
									<div class="text">
										<p>
  											<strong>Nome Completo:</strong>
  											<%= @usuario.nomeCompleto %>
										</p>

										<p>
  											<strong>Cidade:</strong>
 	 										<%= @usuario.cidade %>
										</p>

										<p>
  											<strong>Estado:</strong>
  											<%= @usuario.estado %>	
										</p>

										<p>
  											<strong>Email:</strong>
  											<%= @usuario.email %>
										</p>

										<p>
  											<strong>Descricao Pessoal:</strong>
  											<%= @usuario.descricaoPessoal %>
										</p>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<h2>
			<% random.each do |photo| %>
			<%= link_to (cl_image_tag photo.foto_url(:medium_avatar)),
                photo,
                class: 'fancybox', rel: 'group', title: photo.nomeCompleto, alt: 'Foto' %>
  			<% end %>
			</h2>
	</div>